export interface CountryData {
  code: string;
  name: string;
  dialCode: string;
  phoneLengths: number[];
}

export const COUNTRIES: CountryData[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', phoneLengths: [9] },
  { code: 'AL', name: 'Albania', dialCode: '+355', phoneLengths: [9] },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', phoneLengths: [9] },
  { code: 'AS', name: 'American Samoa', dialCode: '+1-684', phoneLengths: [7] },
  { code: 'AD', name: 'Andorra', dialCode: '+376', phoneLengths: [6] },
  { code: 'AO', name: 'Angola', dialCode: '+244', phoneLengths: [9] },
  { code: 'AI', name: 'Anguilla', dialCode: '+1-264', phoneLengths: [7] },
  { code: 'AQ', name: 'Antarctica', dialCode: '+672', phoneLengths: [6] },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1-268', phoneLengths: [7] },
  { code: 'AR', name: 'Argentina', dialCode: '+54', phoneLengths: [10] },
  { code: 'AM', name: 'Armenia', dialCode: '+374', phoneLengths: [8] },
  { code: 'AW', name: 'Aruba', dialCode: '+297', phoneLengths: [7] },
  { code: 'AU', name: 'Australia', dialCode: '+61', phoneLengths: [9] },
  { code: 'AT', name: 'Austria', dialCode: '+43', phoneLengths: [10, 11] },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', phoneLengths: [9] },
  { code: 'BS', name: 'Bahamas', dialCode: '+1-242', phoneLengths: [7] },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', phoneLengths: [8] },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', phoneLengths: [10] },
  { code: 'BB', name: 'Barbados', dialCode: '+1-246', phoneLengths: [7] },
  { code: 'BY', name: 'Belarus', dialCode: '+375', phoneLengths: [9] },
  { code: 'BE', name: 'Belgium', dialCode: '+32', phoneLengths: [9] },
  { code: 'BZ', name: 'Belize', dialCode: '+501', phoneLengths: [7] },
  { code: 'BJ', name: 'Benin', dialCode: '+229', phoneLengths: [8] },
  { code: 'BM', name: 'Bermuda', dialCode: '+1-441', phoneLengths: [7] },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', phoneLengths: [8] },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', phoneLengths: [8] },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', phoneLengths: [8] },
  { code: 'BW', name: 'Botswana', dialCode: '+267', phoneLengths: [8] },
  { code: 'BR', name: 'Brazil', dialCode: '+55', phoneLengths: [10, 11] },
  { code: 'IO', name: 'British Indian Ocean Territory', dialCode: '+246', phoneLengths: [7] },
  { code: 'VG', name: 'British Virgin Islands', dialCode: '+1-284', phoneLengths: [7] },
  { code: 'BN', name: 'Brunei', dialCode: '+673', phoneLengths: [7] },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', phoneLengths: [9] },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', phoneLengths: [8] },
  { code: 'BI', name: 'Burundi', dialCode: '+257', phoneLengths: [8] },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', phoneLengths: [8, 9] },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', phoneLengths: [9] },
  { code: 'CA', name: 'Canada', dialCode: '+1', phoneLengths: [10] },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', phoneLengths: [7] },
  { code: 'KY', name: 'Cayman Islands', dialCode: '+1-345', phoneLengths: [7] },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', phoneLengths: [8] },
  { code: 'TD', name: 'Chad', dialCode: '+235', phoneLengths: [8] },
  { code: 'CL', name: 'Chile', dialCode: '+56', phoneLengths: [9] },
  { code: 'CN', name: 'China', dialCode: '+86', phoneLengths: [11] },
  { code: 'CX', name: 'Christmas Island', dialCode: '+61', phoneLengths: [9] },
  { code: 'CC', name: 'Cocos Islands', dialCode: '+61', phoneLengths: [9] },
  { code: 'CO', name: 'Colombia', dialCode: '+57', phoneLengths: [10] },
  { code: 'KM', name: 'Comoros', dialCode: '+269', phoneLengths: [7] },
  { code: 'CK', name: 'Cook Islands', dialCode: '+682', phoneLengths: [5] },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', phoneLengths: [8] },
  { code: 'HR', name: 'Croatia', dialCode: '+385', phoneLengths: [9] },
  { code: 'CU', name: 'Cuba', dialCode: '+53', phoneLengths: [8] },
  { code: 'CW', name: 'Curaçao', dialCode: '+599', phoneLengths: [7] },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', phoneLengths: [8] },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', phoneLengths: [9] },
  { code: 'CD', name: 'Democratic Republic of the Congo', dialCode: '+243', phoneLengths: [9] },
  { code: 'DK', name: 'Denmark', dialCode: '+45', phoneLengths: [8] },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', phoneLengths: [8] },
  { code: 'DM', name: 'Dominica', dialCode: '+1-767', phoneLengths: [7] },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1-809', phoneLengths: [7] },
  { code: 'TL', name: 'East Timor', dialCode: '+670', phoneLengths: [7] },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', phoneLengths: [9] },
  { code: 'EG', name: 'Egypt', dialCode: '+20', phoneLengths: [10] },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', phoneLengths: [8] },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', phoneLengths: [9] },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', phoneLengths: [7] },
  { code: 'EE', name: 'Estonia', dialCode: '+372', phoneLengths: [7, 8] },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', phoneLengths: [9] },
  { code: 'FK', name: 'Falkland Islands', dialCode: '+500', phoneLengths: [5] },
  { code: 'FO', name: 'Faroe Islands', dialCode: '+298', phoneLengths: [6] },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', phoneLengths: [7] },
  { code: 'FI', name: 'Finland', dialCode: '+358', phoneLengths: [9, 10] },
  { code: 'FR', name: 'France', dialCode: '+33', phoneLengths: [9] },
  { code: 'GF', name: 'French Guiana', dialCode: '+594', phoneLengths: [9] },
  { code: 'PF', name: 'French Polynesia', dialCode: '+689', phoneLengths: [6] },
  { code: 'GA', name: 'Gabon', dialCode: '+241', phoneLengths: [7] },
  { code: 'GM', name: 'Gambia', dialCode: '+220', phoneLengths: [7] },
  { code: 'GE', name: 'Georgia', dialCode: '+995', phoneLengths: [9] },
  { code: 'DE', name: 'Germany', dialCode: '+49', phoneLengths: [10, 11, 12] },
  { code: 'GH', name: 'Ghana', dialCode: '+233', phoneLengths: [9] },
  { code: 'GI', name: 'Gibraltar', dialCode: '+350', phoneLengths: [8] },
  { code: 'GR', name: 'Greece', dialCode: '+30', phoneLengths: [10] },
  { code: 'GL', name: 'Greenland', dialCode: '+299', phoneLengths: [6] },
  { code: 'GD', name: 'Grenada', dialCode: '+1-473', phoneLengths: [7] },
  { code: 'GP', name: 'Guadeloupe', dialCode: '+590', phoneLengths: [9] },
  { code: 'GU', name: 'Guam', dialCode: '+1-671', phoneLengths: [7] },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', phoneLengths: [8] },
  { code: 'GG', name: 'Guernsey', dialCode: '+44', phoneLengths: [10] },
  { code: 'GN', name: 'Guinea', dialCode: '+224', phoneLengths: [8] },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', phoneLengths: [7] },
  { code: 'GY', name: 'Guyana', dialCode: '+592', phoneLengths: [7] },
  { code: 'HT', name: 'Haiti', dialCode: '+509', phoneLengths: [8] },
  { code: 'HN', name: 'Honduras', dialCode: '+504', phoneLengths: [8] },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', phoneLengths: [8] },
  { code: 'HU', name: 'Hungary', dialCode: '+36', phoneLengths: [9] },
  { code: 'IS', name: 'Iceland', dialCode: '+354', phoneLengths: [7] },
  { code: 'IN', name: 'India', dialCode: '+91', phoneLengths: [10] },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', phoneLengths: [9, 10, 11, 12] },
  { code: 'IR', name: 'Iran', dialCode: '+98', phoneLengths: [10] },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', phoneLengths: [10] },
  { code: 'IE', name: 'Ireland', dialCode: '+353', phoneLengths: [9] },
  { code: 'IM', name: 'Isle of Man', dialCode: '+44', phoneLengths: [10] },
  { code: 'IL', name: 'Israel', dialCode: '+972', phoneLengths: [9] },
  { code: 'IT', name: 'Italy', dialCode: '+39', phoneLengths: [10] },
  { code: 'CI', name: 'Ivory Coast', dialCode: '+225', phoneLengths: [8] },
  { code: 'JM', name: 'Jamaica', dialCode: '+1-876', phoneLengths: [7] },
  { code: 'JP', name: 'Japan', dialCode: '+81', phoneLengths: [10] },
  { code: 'JE', name: 'Jersey', dialCode: '+44', phoneLengths: [10] },
  { code: 'JO', name: 'Jordan', dialCode: '+962', phoneLengths: [9] },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', phoneLengths: [10] },
  { code: 'KE', name: 'Kenya', dialCode: '+254', phoneLengths: [9] },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', phoneLengths: [5, 8] },
  { code: 'KV', name: 'Kosovo', dialCode: '+383', phoneLengths: [8] },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', phoneLengths: [8] },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', phoneLengths: [9] },
  { code: 'LA', name: 'Laos', dialCode: '+856', phoneLengths: [8, 9] },
  { code: 'LV', name: 'Latvia', dialCode: '+371', phoneLengths: [8] },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', phoneLengths: [7, 8] },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', phoneLengths: [8] },
  { code: 'LR', name: 'Liberia', dialCode: '+231', phoneLengths: [7, 8] },
  { code: 'LY', name: 'Libya', dialCode: '+218', phoneLengths: [8, 9] },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', phoneLengths: [7] },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', phoneLengths: [8] },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', phoneLengths: [9] },
  { code: 'MO', name: 'Macau', dialCode: '+853', phoneLengths: [8] },
  { code: 'MK', name: 'Macedonia', dialCode: '+389', phoneLengths: [8] },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', phoneLengths: [9] },
  { code: 'MW', name: 'Malawi', dialCode: '+265', phoneLengths: [7, 9] },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', phoneLengths: [9, 10] },
  { code: 'MV', name: 'Maldives', dialCode: '+960', phoneLengths: [7] },
  { code: 'ML', name: 'Mali', dialCode: '+223', phoneLengths: [8] },
  { code: 'MT', name: 'Malta', dialCode: '+356', phoneLengths: [8] },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', phoneLengths: [7] },
  { code: 'MQ', name: 'Martinique', dialCode: '+596', phoneLengths: [9] },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', phoneLengths: [8] },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', phoneLengths: [7] },
  { code: 'YT', name: 'Mayotte', dialCode: '+262', phoneLengths: [9] },
  { code: 'MX', name: 'Mexico', dialCode: '+52', phoneLengths: [10] },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', phoneLengths: [7] },
  { code: 'MD', name: 'Moldova', dialCode: '+373', phoneLengths: [8] },
  { code: 'MC', name: 'Monaco', dialCode: '+377', phoneLengths: [8, 9] },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', phoneLengths: [8] },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', phoneLengths: [8] },
  { code: 'MS', name: 'Montserrat', dialCode: '+1-664', phoneLengths: [7] },
  { code: 'MA', name: 'Morocco', dialCode: '+212', phoneLengths: [9] },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', phoneLengths: [8, 9] },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', phoneLengths: [7, 8, 9, 10] },
  { code: 'NA', name: 'Namibia', dialCode: '+264', phoneLengths: [9] },
  { code: 'NR', name: 'Nauru', dialCode: '+674', phoneLengths: [7] },
  { code: 'NP', name: 'Nepal', dialCode: '+977', phoneLengths: [10] },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', phoneLengths: [9] },
  { code: 'NC', name: 'New Caledonia', dialCode: '+687', phoneLengths: [6] },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', phoneLengths: [8, 9] },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', phoneLengths: [8] },
  { code: 'NE', name: 'Niger', dialCode: '+227', phoneLengths: [8] },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', phoneLengths: [10] },
  { code: 'NU', name: 'Niue', dialCode: '+683', phoneLengths: [4] },
  { code: 'NF', name: 'Norfolk Island', dialCode: '+672', phoneLengths: [6] },
  { code: 'KP', name: 'North Korea', dialCode: '+850', phoneLengths: [8, 10] },
  { code: 'MP', name: 'Northern Mariana Islands', dialCode: '+1-670', phoneLengths: [7] },
  { code: 'NO', name: 'Norway', dialCode: '+47', phoneLengths: [8] },
  { code: 'OM', name: 'Oman', dialCode: '+968', phoneLengths: [8] },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', phoneLengths: [10] },
  { code: 'PW', name: 'Palau', dialCode: '+680', phoneLengths: [7] },
  { code: 'PS', name: 'Palestine', dialCode: '+970', phoneLengths: [9] },
  { code: 'PA', name: 'Panama', dialCode: '+507', phoneLengths: [8] },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', phoneLengths: [8] },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', phoneLengths: [9] },
  { code: 'PE', name: 'Peru', dialCode: '+51', phoneLengths: [9] },
  { code: 'PH', name: 'Philippines', dialCode: '+63', phoneLengths: [10] },
  { code: 'PN', name: 'Pitcairn', dialCode: '+64', phoneLengths: [8, 9] },
  { code: 'PL', name: 'Poland', dialCode: '+48', phoneLengths: [9] },
  { code: 'PT', name: 'Portugal', dialCode: '+351', phoneLengths: [9] },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1-787', phoneLengths: [7] },
  { code: 'QA', name: 'Qatar', dialCode: '+974', phoneLengths: [8] },
  { code: 'CG', name: 'Republic of the Congo', dialCode: '+242', phoneLengths: [9] },
  { code: 'RE', name: 'Réunion', dialCode: '+262', phoneLengths: [9] },
  { code: 'RO', name: 'Romania', dialCode: '+40', phoneLengths: [9] },
  { code: 'RU', name: 'Russia', dialCode: '+7', phoneLengths: [10] },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', phoneLengths: [9] },
  { code: 'BL', name: 'Saint Barthélemy', dialCode: '+590', phoneLengths: [9] },
  { code: 'SH', name: 'Saint Helena', dialCode: '+290', phoneLengths: [4, 9] },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1-869', phoneLengths: [7] },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1-758', phoneLengths: [7] },
  { code: 'MF', name: 'Saint Martin', dialCode: '+590', phoneLengths: [9] },
  { code: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', phoneLengths: [6] },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1-784', phoneLengths: [7] },
  { code: 'WS', name: 'Samoa', dialCode: '+685', phoneLengths: [7] },
  { code: 'SM', name: 'San Marino', dialCode: '+378', phoneLengths: [10] },
  { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', phoneLengths: [7] },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', phoneLengths: [9] },
  { code: 'SN', name: 'Senegal', dialCode: '+221', phoneLengths: [9] },
  { code: 'RS', name: 'Serbia', dialCode: '+381', phoneLengths: [9] },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', phoneLengths: [7] },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', phoneLengths: [8] },
  { code: 'SG', name: 'Singapore', dialCode: '+65', phoneLengths: [8] },
  { code: 'SX', name: 'Sint Maarten', dialCode: '+1-721', phoneLengths: [7] },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', phoneLengths: [9] },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', phoneLengths: [8] },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', phoneLengths: [5] },
  { code: 'SO', name: 'Somalia', dialCode: '+252', phoneLengths: [8] },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', phoneLengths: [9] },
  { code: 'KR', name: 'South Korea', dialCode: '+82', phoneLengths: [9, 10] },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', phoneLengths: [9] },
  { code: 'ES', name: 'Spain', dialCode: '+34', phoneLengths: [9] },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', phoneLengths: [9] },
  { code: 'SD', name: 'Sudan', dialCode: '+249', phoneLengths: [9] },
  { code: 'SR', name: 'Suriname', dialCode: '+597', phoneLengths: [7] },
  { code: 'SZ', name: 'Swaziland', dialCode: '+268', phoneLengths: [7, 8] },
  { code: 'SE', name: 'Sweden', dialCode: '+46', phoneLengths: [7, 8, 9] },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', phoneLengths: [9] },
  { code: 'SY', name: 'Syria', dialCode: '+963', phoneLengths: [9] },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', phoneLengths: [8, 9] },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', phoneLengths: [9] },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', phoneLengths: [9] },
  { code: 'TH', name: 'Thailand', dialCode: '+66', phoneLengths: [9] },
  { code: 'TG', name: 'Togo', dialCode: '+228', phoneLengths: [8] },
  { code: 'TK', name: 'Tokelau', dialCode: '+690', phoneLengths: [4] },
  { code: 'TO', name: 'Tonga', dialCode: '+676', phoneLengths: [7] },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1-868', phoneLengths: [7] },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', phoneLengths: [8] },
  { code: 'TR', name: 'Turkey', dialCode: '+90', phoneLengths: [10] },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', phoneLengths: [8] },
  { code: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1-649', phoneLengths: [7] },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', phoneLengths: [5] },
  { code: 'UG', name: 'Uganda', dialCode: '+256', phoneLengths: [9] },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', phoneLengths: [9] },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', phoneLengths: [9] },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', phoneLengths: [10] },
  { code: 'US', name: 'United States', dialCode: '+1', phoneLengths: [10] },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', phoneLengths: [8] },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', phoneLengths: [9] },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', phoneLengths: [7] },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', phoneLengths: [10] },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', phoneLengths: [9, 10] },
  { code: 'WF', name: 'Wallis and Futuna', dialCode: '+681', phoneLengths: [6] },
  { code: 'YE', name: 'Yemen', dialCode: '+967', phoneLengths: [9] },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', phoneLengths: [9] },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', phoneLengths: [9] }
];

export const getCountryByDialCode = (dialCode: string): CountryData | undefined => {
  return COUNTRIES.find(c => c.dialCode === dialCode);
};

export const getCountryByName = (name: string): CountryData | undefined => {
  return COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
};

export const validatePhoneNumber = (number: string, countryName?: string): boolean => {
  const digitsOnly = number.replace(/\D/g, '');
  if (!digitsOnly) return false;

  if (countryName) {
    const country = getCountryByName(countryName);
    if (country) {
      return country.phoneLengths.includes(digitsOnly.length);
    }
  }

  // General international length standard fallback
  return digitsOnly.length >= 7 && digitsOnly.length <= 15;
};
